Document Dart team publishers
dart-lang/site-www pull request #2801
Opened 2020-12-14 16:08 UTC by mit-mit

2020-12-14 16:33 UTC, kevmoo approved these changes

2020-12-14 17:53 UTC, kwalrath requested changes
I've rewritten this (so much easier to rewrite than to write from scratch!).

2020-12-14 18:24 UTC, kwalrath commented
I've rewritten this to put everything into one table and to swap the orientation of the table. Also, it appears that dart.dev/packages redirects to pub.dev! (I probably would've renamed the page anyway.)

My version:
https://kw-www-dartlang-1.firebaseapp.com/dart-team-packages

Mit's original (please make sure I didn't miss anything):
https://kw-www-dartlang-1.firebaseapp.com/packages-ORIG

2020-12-14 18:53 UTC, mit-mit commented
That looks great Kathy! But let's wait for a review by Lasse and Nate before we merge.

2020-12-14 18:59 UTC, kwalrath approved these changes

2020-12-14 19:47 UTC, natebosch approved these changes

2020-12-14 19:47 UTC, natebosch commented on src/dart-team-packages.md
> +description: The Dart team publishes package under the verified publishers dart.dev, tools.dart.dev, and labs.dart.dev.
[nit] 
```suggestion
description: The Dart team publishes packages under the verified publishers dart.dev, tools.dart.dev, and labs.dart.dev.
```

2020-12-15 15:09 UTC, lrhn approved these changes
SGTM

2020-12-15 15:10 UTC, merged