correct sample code
dart-lang/site-www pull request #3066
Opened 2021-03-13 17:11 UTC by ngdangtu-vn

On production site: https://dart.dev/guides/language/effective-dart/usage#dont-allow-an-import-path-to-reach-into-or-out-of-lib

The sample code above the line '_Dart thinks those are imports of two completely unrelated libraries._' has wrong a format. It supports to be 2 sample codes. One's good and one's bad each has one line. But it got mixed into one bad sample. Therefore I separated it.

This isn't rocket science, so I didn't do a local build to test. But I make sure to double check the syntax so it should display properly. (The reasons I couldn't do that yet due to I having some trouble with `rvm`.)

2021-03-13 17:13 UTC, ngdangtu-vn commented
@googlebot I signed it!

2021-03-16 01:31 UTC, kwalrath requested changes
Actually, I'm pretty sure that @munificent meant this sample to be the way it is — he's illustrating that the same file imports `api.dart` in two ways.

However, this rule _could_ use a _good_ example, down at the bottom. Maybe something like this:

> Instead, when you need to reach into a package’s lib directory (even from the same package’s test directory or any other top-level directory), use a package: import:
>
> import 'package:my_package/api.dart';
>
> A package should never reach out of its lib directory and import libraries from other places in the package.

2021-03-17 16:27 UTC, ngdangtu-vn reviewed
Then I will remove the 'bad' example which leaves sample only. Also adding the good example as you suggested. How's about it?

2021-03-17 18:06 UTC, kwalrath commented on src/_guides/language/effective-dart/usage.md
> -{:.bad}
We should leave this line in. It's **bad** to import the same library two different ways.

2021-03-17 18:07 UTC, kwalrath commented on src/_guides/language/effective-dart/usage.md
> +<?code-excerpt "test/api_test.dart"?>
We'll need to change the excerpt tag and the test/api_test.dart file to make the build work, but I can handle that.

2021-04-16 22:24 UTC, kwalrath commented
Fixes #3124

2021-04-16 22:25 UTC, kwalrath approved these changes

2021-04-16 22:27 UTC, merged