Update sidenav wrt dart web
dart-lang/site-www pull request #3126
Opened 2021-04-06 20:18 UTC by mit-mit

- Move `dart2js` and `dartdevc` down next to webdev, as most developers should be spawning them via `webdev`

2021-04-06 20:22 UTC, kevmoo approved these changes

2021-04-06 22:02 UTC, kwalrath requested changes
This list was alphabetical. Rather than change that, I'd prefer to either take these pages out of the sidenav or indent them under web, somehow. (Not all the commands need to be in the sidenav, as long as there's a parent page that can represent them. E.g. see https://dart.dev/tools/pub/cmd/pub-cache.)

2021-04-07 13:31 UTC, mit-mit commented
How about we just delete them then? They are already linked from several other pages, incl. https://dart.dev/tools/dart-compile#js and https://dart.dev/tools/webdev.

2021-04-08 22:22 UTC, parlough approved these changes
I agree removing them makes the most sense, as `webdev` should be their primary destination.

You'll have to merge master in or rebase, there's a conflict with your other sidebar changes.

2021-04-08 22:45 UTC, kwalrath approved these changes

2021-04-08 22:55 UTC, merged