added issue reference to todos
dart-lang/site-www pull request #3299
Opened 2021-06-03 18:58 UTC by vendz

in reference to #2119

2021-06-03 19:15 UTC, vendz commented
@googlebot I signed it!

2021-06-03 19:23 UTC, vendz commented
@kwalrath please review my PR

2021-06-03 21:34 UTC, kwalrath reviewed
Thank you, @vendz!

I believe that the test failures are due to line length > 80. Could you break up the lines? While you're at it, you might make these full URLs. Or not. :)

2021-06-04 00:55 UTC, vendz commented
@kwalrath sorry for the late reply as I am from India. Yeah I can do that

2021-06-04 01:16 UTC, vendz commented
@kwalrath I have made changes to the TODO line so if you could review my PR now

2021-06-04 01:23 UTC, vendz commented
@parlough i have made the changes you requested in this PR itself so if you could review it

2021-06-04 02:03 UTC, parlough approved these changes
Some minor suggestions, feel free to ignore them if desired.

Thanks again!

2021-06-04 02:03 UTC, parlough commented on null_safety_examples/misc/lib/tutorial/stream_interface.dart
>  // as follows, but it isn't: {bool Function(dynamic error) test}.
Can you instead put a link to the issue so its easier to access when navigating the source?

```suggestion
// TODO(chalin): I believe that handleError's test argument should be declared
// as follows, but it isn't: {bool Function(dynamic error) test}.
// (https://github.com/dart-lang/site-www/issues/3298)
```

2021-06-04 02:03 UTC, parlough commented on null_safety_examples/misc/test/language_tour/browser_test.dart
> +    // TODO(miquelbeltran) Maybe ! would be better here (#3295)
Including the issue link here would be great as well. 

```suggestion
    // TODO(miquelbeltran) Maybe ! would be better here
    // (https://github.com/dart-lang/site-www/issues/3295)
```

2021-06-04 02:12 UTC, vendz commented
@parlough made the changes you requested.

2021-06-04 02:44 UTC, parlough commented
@vendz Thanks for all the work, looks good to me! I'm running the checks and if they're all green, I'll merge these changes :)

2021-06-04 02:46 UTC, parlough requested changes

2021-06-04 02:46 UTC, parlough commented on null_safety_examples/misc/lib/language_tour/functions.dart
> +
```suggestion
```

2021-06-04 02:46 UTC, parlough commented on null_safety_examples/misc/test/language_tour/browser_test.dart
> +
```suggestion
```

2021-06-04 02:47 UTC, parlough approved these changes

2021-06-04 02:51 UTC, merged

2021-06-04 02:53 UTC, parlough commented
All tests were green after I removed the extra whitespace and the changes have been committed to the main branch(https://github.com/dart-lang/site-www/commit/c95f9bb1fee6029e7429540417318b0754ee172d). Thanks again and good work and communication around your first contribution :D