Removed redundant text
dart-lang/site-www pull request #3690
Opened 2021-11-25 19:43 UTC by nitin-singla

"ⓘ Note: Note:" changed to "ⓘ Note:"

2021-11-25 20:00 UTC, nitin-singla commented
I have accepted the CLA, can you please do a workflow re-run?

2021-11-26 02:41 UTC, domesticmouse approved these changes

2021-11-26 03:09 UTC, parlough approved these changes

2021-11-26 03:15 UTC, parlough requested changes
Thanks for the PR! It seems the email attached to the commit may be misconfigured and not match what you signed the CLA with.

It seems the commit was made with `nitin-singla <nitingithub.com>` set as the username and email combo. Here are some instructions on setting the git email: https://docs.github.com/en/github-ae@latest/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

2021-11-27 01:51 UTC, parlough approved these changes
Looks great to me, nice catch and I'm glad you got the commit authorship figured out. Thanks again!

2021-11-27 01:51 UTC, merged