Tone down Flutter message in /get-dart
dart-lang/site-www pull request #3779
Opened 2022-01-24 11:17 UTC by mit-mit

2022-01-24 12:26 UTC, domesticmouse approved these changes

2022-01-24 21:16 UTC, kwalrath reviewed
This needs a couple of style/grammar changes, but overall... How about making this a real note up above, rather than an off-brand note down below? I'll stage an example of what I mean.

2022-01-24 21:25 UTC, kwalrath commented
OK, how about these words: https://kw-www-dartlang-1.web.app/get-dart

2022-01-24 21:29 UTC, kwalrath requested changes

2022-01-24 21:29 UTC, kwalrath commented on src/get-dart/index.md
```suggestion

{{site.alert.tip}}
  If you already have the [Flutter SDK],
  then you already have the Dart SDK.
  The [`dart`](/tools/dart-tool) tool
  is in the Flutter SDK's `bin` folder.
{{site.alert.end}}

[Flutter SDK]: {{site.flutter_docs}}/get-started/install
```

2022-01-24 21:29 UTC, kwalrath commented on src/get-dart/index.md
> +
it's -> its, but overall I think it's good to say this sooner rather than later.

```suggestion
```

2022-01-24 21:29 UTC, kwalrath commented on src/get-dart/index.md
You can see this at https://kw-www-dartlang-1.web.app/get-dart

2022-01-25 07:48 UTC, mit-mit commented
> How about making this a real note up above, rather than an off-brand note down below?

I find that too distracting, both visually and placement wise. Most users on this page really shouldn't need to be reminded of it, I feel

2022-01-25 18:37 UTC, kwalrath commented
> > How about making this a real note up above, rather than an off-brand note down below?
> 
> I find that too distracting, both visually and placement wise. Most users on this page really shouldn't need to be reminded of it, I feel

It'd be nice if we had some data to back up our gut feelings. I'm fine with making it not be a big green box if people don't usually need it, but I feel fairly strongly that, content-wise, it should be above the heading for the download procedure.

2022-02-03 12:02 UTC, mit-mit commented
> It'd be nice if we had some data to back up our gut feelings.

Do we have any data that suggests the opposite (i.e. that anyone actually downloads the Dart SDK in error)?

2022-02-08 20:15 UTC, sfshaza2 reviewed
I'm happy to approve and land this, but the "it's" error needs to be fixed (to "its").

2022-02-08 21:00 UTC, mit-mit commented
> the "it's" error needs to be fixed (to "its").

certainly, done @sfshaza2 !

2022-02-08 21:55 UTC, sfshaza2 approved these changes
lgtm!

2022-02-08 21:55 UTC, merged

2022-02-08 22:02 UTC, parlough commented
Thanks everyone!