Fix a typo in async-await.md
dart-lang/site-www pull request #3847
Opened 2022-02-20 03:45 UTC by thezjy

2022-02-20 03:50 UTC, domesticmouse commented
PTAL @parlough

2022-02-20 05:29 UTC, parlough requested changes
Thanks for fixing this! I accidentally messed this up when the tests weren't working properly.

You'll also need to switch the `void` back to `Future<void>` in the example code as well: https://github.com/dart-lang/site-www/blob/main/examples/async_await/bin/get_order.dart#L14

Let me know if you have any issues :)

2022-02-20 05:29 UTC, parlough commented on src/codelabs/async-await.md
> +Future<void> main() async { ··· }
We want to highlight the `Future` here :)

```suggestion
[!Future<void>!] main() async { ··· }
```

2022-02-20 06:22 UTC, domesticmouse approved these changes

2022-02-21 14:40 UTC, parlough approved these changes
Thanks again for catching that we accidentally changed this and fixing it!

2022-02-21 14:45 UTC, merged