Add preview riscv64 mention and support to get-dart
dart-lang/site-www pull request #3959
Opened 2022-04-02 22:04 UTC by parlough

Waiting on a build of riscv64 being released to dev and/or beta branches.

2022-04-06 17:10 UTC, parlough commented
@mit-mit Can you take a look at this now that riscv builds are in the latest dev build? Thanks!

2022-04-06 20:52 UTC, domesticmouse approved these changes

2022-04-07 12:41 UTC, mit-mit requested changes
Thanks! Some detailed changes requested

2022-04-07 12:41 UTC, mit-mit commented on src/get-dart/index.md
> +  Support for riscv4 is in preview, and is available only in the dev channel.
s/for riscv4/for RISC-V/

2022-04-07 12:41 UTC, mit-mit commented on src/get-dart/dart_sdk_archive/lib/src/util.dart
> +  'riscv64': 'riscv64',
s/'riscv64':/'RISC-V (RV64GC)':/

2022-04-07 12:41 UTC, mit-mit commented on src/get-dart/dart_sdk_archive/lib/src/util.dart
> +    PlatformVariant('riscv64', ['Dart SDK']),
s/'riscv64':/'RISC-V (RV64GC)':/

2022-04-07 12:41 UTC, mit-mit commented on src/get-dart/index.md
> +* **Supported architectures:** x64, ia32, arm64, arm, _riscv64_.<br>
Let's change this to:

```
**Supported architectures:** x64, IA32, ARM64, ARM, RISC-V (RV64GC).<br>
```

2022-04-08 11:44 UTC, mit-mit approved these changes
Thanks!

2022-04-08 14:34 UTC, merged