Remove a few older version mentions
dart-lang/site-www pull request #4310
Opened 2022-10-21 18:43 UTC by parlough

2022-10-21 20:23 UTC, atsansone requested changes
@parlough : A few tweaks.

2022-10-21 20:30 UTC, domesticmouse approved these changes

2022-10-22 01:02 UTC, parlough commented on src/tools/pub/pubspec.md
>  displays a warning if your pubspec has an `author` or `authors` section.
I decided to completely remove this section.

2022-10-23 07:28 UTC, atsansone approved these changes
LGTM

2022-10-23 23:27 UTC, merged