Remove mention of initial lack of generic methods
dart-lang/site-www pull request #4328
Opened 2022-10-28 07:29 UTC by parlough

2022-10-28 08:48 UTC, domesticmouse approved these changes

2022-10-28 15:00 UTC, atsansone commented on src/_guides/language/language-tour.md
> +Type arguments are also allowed on methods and functions:
**nit:** [Use active voice](https://developers.google.com/style/voice) please!
```suggestion
Methods and functions allow type arguments.
```

2022-10-28 15:00 UTC, atsansone requested changes
@parlough : Update the language for active voice.

2022-10-31 16:57 UTC, atsansone approved these changes
@parlough : LGTM!

2022-10-31 18:35 UTC, merged