Remove jquery usage in install.js
dart-lang/site-www pull request #4410
Opened 2022-12-01 20:44 UTC by parlough

Also removes some code and functionality that is no longer used.

2022-12-01 22:36 UTC, domesticmouse approved these changes

2022-12-02 18:31 UTC, atsansone requested changes
@parlough : I would recommend replacing the channel descriptions with more parallel and concise language. Suggestion included.

2022-12-02 20:44 UTC, parlough commented on src/get-dart/index.md
>  * **Stable** channel: **stable releases**, updated roughly every three months;
I would rather keep those changes separate from the JS updates here. I'll open a follow-up PR.

2022-12-05 18:55 UTC, atsansone commented on src/get-dart/index.md
>  * **Stable** channel: **stable releases**, updated roughly every three months;
Done as https://github.com/dart-lang/site-www/issues/4414.

2022-12-05 18:55 UTC, atsansone approved these changes
LGTM for original scope of changes.

2022-12-05 18:58 UTC, parlough commented on src/get-dart/index.md
>  * **Stable** channel: **stable releases**, updated roughly every three months;
Thanks!

2022-12-05 18:59 UTC, merged