Improve word breaking/wraping in TOC on underscores
dart-lang/site-www pull request #4562
Opened 2023-01-31 03:33 UTC by parlough

Currently in the right-hand TOC (table of contents), on long strings with underscores (`_`), such as on the linter rules and diagnostic messages page. They are just wrapped/broken on the first character convenient. This PR introduces a line break opportunity element ([`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr)) after each underscore (`_`) in the TOC. This allows the browser to prefer to wrap just after an underscore if its needed. This allows the reader to know it continues on the next line and just looks nicer and more consistent.

To see the improvements, visit the old linter rule and diagnostic pages, with your screen wide enough to see the TOC.

Old linter rules: https://dart.dev/tools/linter-rules
New linter rules:

Old diagnostic messages: https://dart.dev/tools/diagnostic-messages
New diagnostic messages:

2023-01-31 17:05 UTC, atsansone requested changes
@parlough : Two relevant misspellings.

2023-01-31 17:05 UTC, atsansone commented on src/_plugins/underscore_breaker.rb
> +  def underscore_breaker(string_to_break, in_achor = false)
**issue:** Misspelled `anchor`.
```suggestion
  def underscore_breaker(string_to_break, in_anchor = false)
```

2023-01-31 17:05 UTC, atsansone commented on src/_plugins/underscore_breaker.rb
> +    if in_achor then
**issue:** Misspelled `anchor`.
```suggestion
    if in_anchor then
```

2023-01-31 18:39 UTC, parlough commented on src/_plugins/underscore_breaker.rb
> +  def underscore_breaker(string_to_break, in_achor = false)
Typing just hasn't been my friend these past few days! Thanks.

2023-01-31 18:46 UTC, parlough commented
@atsansone I've made those fixes and would like someone else to review this as well, but what do you think of this change in general?

2023-02-01 20:52 UTC, atsansone approved these changes

2023-02-01 23:22 UTC, domesticmouse approved these changes
It's been so long since I last wrote Ruby that this just looks like perl to me.

2023-02-01 23:24 UTC, parlough commented
One day I'll be able to just write this all in Dart instead...

Thanks for taking a look though!

2023-02-02 18:52 UTC, merged