Update create-library-packages.md
dart-lang/site-www pull request #4648
Opened 2023-03-12 14:45 UTC by kossyl

Delete one 'the' in sentence "When ..."

2023-03-12 23:47 UTC, domesticmouse requested changes
Please sign the CLA. We can't land this PR without it.

Also, consider re-splitting the line to get the markdown under 80 characters wide.

2023-03-22 07:21 UTC, parlough commented on src/_guides/libraries/create-library-packages.md
> +When importing a library file from another package, use the `package:` directive to specify the URI of that file.
We aim to keep each line <= 80 characters and to use some sort of semantic line break: https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks

```suggestion
When importing a library file from another package, use
the `package:` directive to specify the URI of that file.
```

2023-03-22 07:22 UTC, parlough commented
Hi @kossyl, thanks for working on this. I just wanted to check in, as we can't merge this change until the CLA is signed as outlined in [the comment by the google-cla bot](https://github.com/dart-lang/site-www/pull/4648#issuecomment-1465217862).

Let us know if you have any questions. Thanks again!

2023-03-24 17:53 UTC, parlough approved these changes
Thanks so much for catching and fixing this @kossyl, looks good to me!

2023-03-24 21:13 UTC, merged