Changed link on concurrency page
dart-lang/site-www pull request #4973
Opened 2023-06-09 18:13 UTC by atsansone

Fixes #4408

2023-06-09 18:29 UTC, MaryaBelanger requested changes
I'm inclined to go with Paul's comment saying the original link is better. And then, as the user said, instead change the wording so it's clearer:

> the use of isolates doesn't prevent the user's code from experiencing race conditions, it just prevents data races.
> 
> I just want this point to be communicated clearly in the docs.

That clarification wouldn't really make sense to add where the link in question is actually mentioned, since isolates aren't even introduced at that point, but maybe a few lines down after 176.

I can take over the PR and implement this, just lmk or reassign me.

2023-06-09 18:46 UTC, atsansone commented
@MaryaBelanger : Take it. No issues here.

2023-06-12 18:07 UTC, MaryaBelanger commented
@stereotype441 this is a very small change, but I'd appreciate it if you could confirm the wording is still technically correct (lifted entirely from #4408)

2023-06-13 20:27 UTC, MaryaBelanger commented on src/language/concurrency/index.md
> +[error prone](https://en.wikipedia.org/wiki/Race_condition#Data_race) and
Thanks Paul! Opinions help a lot :)

2023-06-13 20:31 UTC, MaryaBelanger commented on src/language/concurrency/index.md
> +[error prone](https://en.wikipedia.org/wiki/Race_condition#Data_race) and
```suggestion
[error prone](https://en.wikipedia.org/wiki/Race_condition#In_software) and
```

2023-06-14 03:59 UTC, atsansone commented
@MaryaBelanger : Made a slight change off your change. Have a look. I hope we can approve and merge soon.

2023-06-14 15:27 UTC, MaryaBelanger approved these changes
@atsansone Thanks for fixing that parenthetical!

2023-06-14 16:21 UTC, merged

2023-06-14 18:27 UTC, mmcdon20 commented
I'm satisfied with these changes. Thanks @MaryaBelanger, @atsansone, @stereotype441.