Removed the latest keyword from the docs, fix issue #5233
dart-lang/site-www pull request #5234
Opened 2023-10-09 06:48 UTC by abinvs-2019

Removed the "latest" keyword from the showing int the dart version, which currently shows 2.19.6 and it is not the latest one.

Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

Fixes  #5233

--- 

- [ ] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [ ] This PR doesn’t contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

2023-10-09 15:36 UTC, parlough requested changes
Hi, thanks for the pull request!

I can see where the confusion comes from, but the intention was that users would install the latest version of 2.19.x, not just 2.19.0. 

So that remains clear, how about we change the text and headers to "Switch to the Dart 2.19.6 release" or similar? Originally we didn't do that since there were potentially more 2.19 releases, but there haven't been for a long time, so I think being specific would be fine. 

What do you think?

2023-10-10 04:35 UTC, abinvs-2019 commented
@parlough Yes i think that would be fine, specifying the version would be more detailed.

2023-10-10 16:55 UTC, parlough reviewed
Thanks for letting me know your thoughts!

The following suggestions should update it to be more specific:

2023-10-10 16:55 UTC, parlough commented on src/null-safety/migration-guide.md
> +  use the   Dart 2.19 SDK.
```suggestion
  use the Dart 2.19.6 SDK.
```

2023-10-10 16:55 UTC, parlough commented on src/null-safety/migration-guide.md
> +### Switch to the   Dart 2.19 release
```suggestion
### Switch to the Dart 2.19.6 release
```

2023-10-10 16:55 UTC, parlough commented on src/null-safety/migration-guide.md
> +Switch to the   **Dart 2.19 release** of the Dart SDK.
```suggestion
Switch to the **2.19.6 release** of the Dart SDK. 
```

2023-10-10 16:55 UTC, parlough commented on src/null-safety/migration-guide.md
>  This is included in the Flutter 3.7 SDK.
```suggestion
This is included in the Flutter 3.7.12 SDK.
```

2023-10-10 16:55 UTC, parlough commented on src/null-safety/migration-guide.md
> +1. Run `dart pub upgrade --null-safety` to upgrade to the   versions
```suggestion
1. Run `dart pub upgrade --null-safety` to upgrade to the versions
```

2023-10-12 16:38 UTC, parlough approved these changes
Thank you for this PR and making those adjustments!

Looks good to me :)

2023-10-13 02:54 UTC, merged